### ISSUE TITLE
Update fresh in import map

### ISSUE THREAD

**Issue by khuongduybui** [EccentricVamp/freshwind#2]
Since fresh 1.1, the starter code use `$fresh` instead of `fresh`.
The import map should be updated to stay in sync, and the import statement in `freshwind.ts` should be updated too.

**Comment by EccentricVamp** [comment]
Fixed by 146448c0554688779e0fa7d3b91321f4b24826dd

Published in Freshwind 2.0.0

Thanks for pointing it out!
