### ISSUE TITLE
Doesn't seem to work with plain-text class names?

### ISSUE THREAD

**Issue by khuongduybui** [EccentricVamp/freshwind#3]
I updated my import map to match the `twind` version used in this code repo and use the plugin in place of the official one.
`tw.target` seems to not pick up anything in plain-text class names. I currently have to wrap them all in `tw()`.

**Comment by khuongduybui** [comment]
I think we're missing this https://github.com/denoland/fresh/blob/1b3c9f2569c5d56a6d37c366cb5940f26b7e131e/plugins/twind/shared.ts#L30

**Comment by EccentricVamp** [comment]
I think you're right. Unfortunately, that setup depends on ~~hydration~~ snapshots which I haven't figured out yet (see #1).

It may be a while before I find time to figure out how to get Twind v1 snapshots to work with Fresh. If you have more knowledge or time than me, you're welcome to take a crack at it!

**Comment by EccentricVamp** [comment]
Freshwind 3.0.0-beta should fix this issue

**Comment by khuongduybui** [comment]
I tried 3.0.0, which seems to work but besides the duplicate styles you mention in #4, I also see an ugly flash when the page first loads and the styles have not been loaded.

That behavior can be consistently observed here: https://fresh-flowbite.deno.dev/
The source code for that demo site is here: https://github.com/khuongduybui/fresh-flowbite-site

**Comment by EccentricVamp** [comment]
Thanks for pointing out the flash. I'm going to close this issue for now, and open up a [separate issue](https://github.com/EccentricVamp/freshwind/issues/5) for the flash.

**Comment by EccentricVamp** [comment]
@khuongduybui, the flashing should be fixed in Freshwind 4.0.0. I was able to replicate the issue running your test site locally (thanks for sharing that by the way). And I was able to confirm that it's fixed locally.

There are some breaking changes (hence the major version change). I've added a usage section to the readme that should make it pretty straightforward to upgrade.

**Comment by khuongduybui** [comment]
I'm glad you figured it out! Thanks for the quick investigation. I planned to give it a look tomorrow but since you got it already I will wait to see the PR!
